"""

Each new term in the Fibonacci sequence is generated by adding
the previous two terms. By starting with 1 and 2, the first 10 terms
will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values
do not exceedfour million, find the sum of the even-valued terms.

"""

pre,fib,tally=0,1,0 #initialize variables, pre is last term fib is current
MAX=4000000 #4million is maximum value of a term

while fib <= MAX: 
    if(fib%2): tally+=fib #add to tally is fib term is even
        
    pre,fib=fib,pre+fib #get new values for pre and fib
   

print("\ntally is: ",tally) #print result
input("\n[press ENTER to end program]")

